create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 60),
  email text not null unique check (char_length(email) between 3 and 254),
  source text not null default 'find_your_flavor' check (source in ('find_your_flavor', 'friend_share')),
  flavor text,
  page_url text
);

alter table public.waitlist enable row level security;

comment on table public.waitlist is 'Cookie:Ro Bakery launch waitlist. Private; accessed by the Vercel server with the service-role key.';
comment on column public.waitlist.source is 'find_your_flavor or friend_share';
