const FLAVORS={cotton:{id:'cotton',emoji:'☁️',name:'Cotton Candy Cookie',short:'Cotton Candy',color:'#F2B8D8',accent:'#A8C9F7',tagline:'몽글몽글한 빛과 설레는 장면이 가득한, 솜사탕처럼 달콤한 여행이었네요.',keywords:['파스텔','부드러운 빛','동화 같은 분위기']},lemon:{id:'lemon',emoji:'🍋',name:'Lemon Cream Cookie',short:'Lemon Cream',color:'#F2D982',accent:'#FFF1BD',tagline:'햇살 가득한 거리와 산뜻한 순간들이 레몬크림처럼 상큼하게 남은 여행이에요.',keywords:['맑은 낮','산뜻한 색감','도시 산책']},mango:{id:'mango',emoji:'🥭',name:'Mango Soda Cookie',short:'Mango Soda',color:'#F0A34C',accent:'#71C7D0',tagline:'햇살과 바닷바람이 톡톡 터지는, 망고소다처럼 자유로운 여행이었네요.',keywords:['강한 햇살','청량한 색감','여름 에너지']},matcha:{id:'matcha',emoji:'🍵',name:'Matcha Latte Cookie',short:'Matcha Latte',color:'#93A878',accent:'#E9DDC7',tagline:'조용한 골목과 느린 오후가 어우러진, 말차라떼처럼 차분한 여행이에요.',keywords:['차분한 톤','자연스러운 초록','느린 분위기']},midnight:{id:'midnight',emoji:'🍫',name:'Midnight Choco Cookie',short:'Midnight Choco',color:'#4E3A42',accent:'#776CA4',tagline:'야경과 즉흥적인 순간들이 진하게 남은, 미드나잇 초코 같은 여행이었네요.',keywords:['어두운 시간대','강한 대비','도시의 밤']}};
let selectedFiles=[],currentFlavor=null,inviterFlavor=null,inviterName='';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],screens=$$('.screen');
function showScreen(id){screens.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function setCookieVisual(el,f){el.style.background=`radial-gradient(circle at 24% 28%,rgba(255,255,255,.34) 0 8%,transparent 9%),radial-gradient(circle at 70% 65%,${f.accent} 0 5%,transparent 6%),radial-gradient(circle at 35% 70%,${f.accent} 0 4%,transparent 5%),linear-gradient(145deg,${f.color},#9A633C)`}
function parseInvite(){const p=new URLSearchParams(location.search),f=p.get('f'),from=p.get('from');if(f&&FLAVORS[f]){inviterFlavor=FLAVORS[f];inviterName=from||'친구';$('#friendSender').textContent=inviterName;$('#friendFlavorName').textContent=inviterFlavor.short;$('#friendFlavorChip').textContent=inviterFlavor.emoji;$('#friendFlavorChip').style.background=inviterFlavor.color;showScreen('screen-friend')}}
$('#startBtn').onclick=()=>showScreen('screen-upload');$('#friendStartBtn').onclick=()=>showScreen('screen-upload');$('#resetBtn').onclick=()=>{history.replaceState({},'',location.pathname);selectedFiles=[];currentFlavor=null;inviterFlavor=null;inviterName='';$('#previewGrid').innerHTML='';$('#photoInput').value='';$('#analyzeBtn').disabled=true;showScreen('screen-home')};
$('#photoInput').addEventListener('change',e=>{selectedFiles=[...e.target.files].filter(f=>f.type.startsWith('image/')).slice(0,2);renderPreviews()});
function renderPreviews(){const g=$('#previewGrid');g.innerHTML='';selectedFiles.forEach((f,i)=>{const u=URL.createObjectURL(f),c=document.createElement('div');c.className='preview-card';c.innerHTML=`<img src="${u}" alt="선택한 여행 사진 ${i+1}"><button type="button">×</button>`;c.querySelector('button').onclick=()=>{selectedFiles.splice(i,1);renderPreviews()};g.appendChild(c)});$('#analyzeBtn').disabled=selectedFiles.length<1}
async function extractFeatures(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const canvas=$('#analysisCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true}),w=96,h=Math.max(64,Math.round(img.height/img.width*w));canvas.width=w;canvas.height=h;ctx.drawImage(img,0,0,w,h);const d=ctx.getImageData(0,0,w,h).data;let r=0,g=0,b=0,n=0,bright=0,sat=0,blue=0,green=0,warm=0,dark=0,pastel=0;for(let i=0;i<d.length;i+=16){const R=d[i],G=d[i+1],B=d[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B),br=(R+G+B)/3;r+=R;g+=G;b+=B;n++;bright+=br;sat+=(mx-mn);if(B>R*1.05&&B>G*.95)blue++;if(G>R*.95&&G>B*1.05)green++;if(R>G*1.05&&G>B*.9)warm++;if(br<78)dark++;if(br>170&&(mx-mn)<65)pastel++}resolve({r:r/n,g:g/n,b:b/n,brightness:bright/n,saturation:sat/n,blue:blue/n,green:green/n,warm:warm/n,dark:dark/n,pastel:pastel/n})};img.onerror=reject;img.src=URL.createObjectURL(file)})}
function chooseFlavor(fs){const f=fs.reduce((a,x)=>(Object.keys(x).forEach(k=>a[k]=(a[k]||0)+x[k]),a),{});Object.keys(f).forEach(k=>f[k]/=fs.length);const s={cotton:0,lemon:0,mango:0,matcha:0,midnight:0};s.midnight+=Math.max(0,(110-f.brightness)/2.8)+f.dark*42+Math.max(0,(f.saturation-70)/4);s.matcha+=f.green*38+((f.brightness>90&&f.brightness<175)?14:0)+Math.max(0,(65-f.saturation)/5);s.mango+=f.blue*25+f.warm*15+Math.max(0,(f.brightness-145)/4)+Math.max(0,(f.saturation-55)/5);s.lemon+=Math.max(0,(f.brightness-155)/3.5)+f.warm*18+((f.saturation<85)?10:0);s.cotton+=f.pastel*45+Math.max(0,(f.brightness-165)/4)+((f.saturation<70)?10:0);const sig=Math.round(f.r*3+f.g*5+f.b*7)%5;Object.keys(s).forEach((k,i)=>s[k]+=(i===sig?.35:0));const id=Object.entries(s).sort((a,b)=>b[1]-a[1])[0][0],ev=[];if(f.brightness>170)ev.push('밝은 자연광');else if(f.brightness<105)ev.push('깊은 야간 톤');else ev.push('부드러운 중간 밝기');if(f.blue>.18)ev.push('청량한 블루 계열');if(f.green>.16)ev.push('자연스러운 그린 계열');if(f.warm>.18)ev.push('따뜻한 햇살 톤');if(f.pastel>.22)ev.push('파스텔·저대비 색감');if(f.saturation>82)ev.push('선명한 색 에너지');if(f.saturation<52)ev.push('차분한 저채도');return{flavor:FLAVORS[id],evidence:[...new Set(ev)].slice(0,3)}}
$('#analyzeBtn').onclick=async()=>{if(!selectedFiles.length)return;showScreen('screen-loading');const t=['사진 속 햇살과 색감을 보고 있어요.','여행의 온도와 리듬을 섞고 있어요.','쿠키에 어울리는 맛을 찾고 있어요.'];let p=0;const timer=setInterval(()=>{p=Math.min(94,p+Math.floor(Math.random()*16)+7);$('#progressBar').style.width=p+'%';$('#loadingText').textContent=t[Math.min(t.length-1,Math.floor(p/34))]},330);try{const features=await Promise.all(selectedFiles.map(extractFeatures));await new Promise(r=>setTimeout(r,1250));const result=chooseFlavor(features);currentFlavor=result.flavor;clearInterval(timer);$('#progressBar').style.width='100%';setTimeout(()=>{renderResult(result);if(inviterFlavor)renderMatchAfterResult(result.flavor);else showScreen('screen-result')},350)}catch(e){clearInterval(timer);currentFlavor=FLAVORS.lemon;renderResult({flavor:currentFlavor,evidence:['밝은 여행 장면','산뜻한 색감']});showScreen('screen-result')}};
function renderResult(r){const f=r.flavor;$('#flavorEmoji').textContent=f.emoji;$('#flavorName').textContent=f.name;$('#flavorTagline').textContent=f.tagline;$('#evidenceBox').innerHTML=(r.evidence.length?r.evidence:f.keywords).map(x=>`<span>${x}</span>`).join('');setCookieVisual($('#flavorCookie'),f)}
$$('.pill-btn').forEach(b=>b.onclick=()=>{$('#feedbackMsg').textContent=b.dataset.feedback==='yes'?'좋아요! 파일럿 Flavor 정확도 개선에 활용할 수 있어요.':'좋아요. 왜 이 맛이 나왔는지 납득되는지도 함께 볼게요.'});$('#jarBtn').onclick=()=>{setCookieVisual($('#jarCookie'),currentFlavor);$('#jarCopy').textContent=`${currentFlavor.emoji} ${currentFlavor.name}가 당신의 첫 여행 쿠키로 저장됐어요.`;showScreen('screen-jar')};
function buildShareUrl(){const name=($('#senderName').value||'친구').trim(),u=new URL(location.href);u.search='';u.searchParams.set('f',currentFlavor.id);u.searchParams.set('from',name);return u.toString()}
async function shareInvite(){const url=buildShareUrl(),name=($('#senderName').value||'친구').trim(),text=`${name}에게 이 여행은 ${currentFlavor.emoji} ${currentFlavor.short} 맛이었어요. 당신에게도 같은 맛일까요?`;if(navigator.share){try{await navigator.share({title:'Cookie:Ro — 우리 여행, 같은 맛일까?',text,url});return}catch(e){}}await navigator.clipboard.writeText(url);$('#shareStatus').textContent='공유 링크를 복사했어요 🍪'}
$('#shareBtn').onclick=shareInvite;$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(buildShareUrl());$('#shareStatus').textContent='링크 복사 완료! 친구에게 보내보세요 🍪'};
function renderMatchAfterResult(receiver){const same=inviterFlavor.id===receiver.id;$('#matchEyebrow').textContent=same?"IT'S A FLAVOR MATCH!":'SAME TRIP, DIFFERENT FLAVOR.';$('#matchTitle').textContent=same?'둘에게 이 여행은 같은 맛으로 남았어요. 🍪🍪':'같은 여행도 서로 다르게 기억되니까.';$('#compareSenderLabel').textContent=inviterName;$('#senderFlavorText').textContent=`${inviterFlavor.emoji} ${inviterFlavor.short}`;$('#receiverFlavorText').textContent=`${receiver.emoji} ${receiver.short}`;setCookieVisual($('#senderMiniCookie'),inviterFlavor);setCookieVisual($('#receiverMiniCookie'),receiver);$('#matchCopy').textContent=same?`${inviterName}와 당신 모두 이 여행을 ${inviterFlavor.short}의 분위기로 기억하고 있네요.`:`${inviterName}에게는 ${inviterFlavor.short}, 당신에게는 ${receiver.short}. 같은 장소도 각자의 시선으로 다른 맛이 될 수 있어요.`;showScreen('screen-match')}
$('#shareResultBtn').onclick=async()=>{const same=inviterFlavor&&inviterFlavor.id===currentFlavor.id,text=same?`우리 여행은 둘 다 ${currentFlavor.emoji} ${currentFlavor.short}! It's a Flavor Match 🍪🍪`:`Same trip, different flavor 🍪 ${inviterName}: ${inviterFlavor?.short} / 나: ${currentFlavor.short}`;if(navigator.share){try{await navigator.share({title:'Cookie:Ro Flavor Result',text,url:location.href});return}catch(e){}}await navigator.clipboard.writeText(text);alert('비교 결과 문구를 복사했어요!')};$('#newTripBtn').onclick=()=>{history.replaceState({},'',location.pathname);inviterFlavor=null;inviterName='';selectedFiles=[];$('#previewGrid').innerHTML='';$('#photoInput').value='';$('#analyzeBtn').disabled=true;showScreen('screen-home')};parseInvite();
